begin;

insert into
    public.exercises (
        id,
        name,
        nickname,
        body_part,
        exercise_type,
        created_by,
        created_at,
        updated_at,
        archived_at
    )
values
    (
        gen_random_uuid (),
        'Barbell Back Squat',
        'Squat',
        'legs',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Front Squat',
        null,
        'legs',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'High Bar Squat',
        null,
        'legs',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Low Bar Squat',
        null,
        'legs',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Paused Squat',
        null,
        'legs',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Bulgarian Split Squat',
        'BSS',
        'legs',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Walking Lunge',
        null,
        'legs',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Reverse Lunge',
        null,
        'legs',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Leg Press',
        null,
        'legs',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Hack Squat',
        null,
        'legs',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Goblet Squat',
        null,
        'legs',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Romanian Deadlift',
        'RDL',
        'legs',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Stiff-Leg Deadlift',
        'SLDL',
        'legs',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Conventional Deadlift',
        'Deadlift',
        'legs',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Sumo Deadlift',
        null,
        'legs',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Trap Bar Deadlift',
        null,
        'legs',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Hip Thrust',
        null,
        'legs',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Barbell Glute Bridge',
        'Glute Bridge',
        'legs',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Leg Extension',
        null,
        'legs',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Seated Leg Curl',
        null,
        'legs',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Lying Leg Curl',
        null,
        'legs',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Standing Calf Raise',
        'Calf Raise',
        'legs',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Seated Calf Raise',
        null,
        'legs',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Flat Barbell Bench Press',
        'Bench',
        'chest',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Paused Bench Press',
        null,
        'chest',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Close Grip Bench Press',
        'CGBP',
        'chest',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Incline Barbell Bench Press',
        'Incline Bench',
        'chest',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Incline Dumbbell Press',
        'Incline DB Press',
        'chest',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Flat Dumbbell Press',
        'DB Bench',
        'chest',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Machine Chest Press',
        null,
        'chest',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Smith Machine Bench Press',
        'Smith Bench',
        'chest',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Chest Fly Machine',
        'Pec Deck',
        'chest',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Cable Chest Fly',
        'Cable Fly',
        'chest',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Push-Up',
        null,
        'chest',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Weighted Push-Up',
        null,
        'chest',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Dips',
        null,
        'chest',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Chest Dip',
        null,
        'chest',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Barbell Row',
        'BB Row',
        'back',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Pendlay Row',
        null,
        'back',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Chest Supported Row',
        null,
        'back',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Seated Cable Row',
        'Cable Row',
        'back',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'One-Arm Dumbbell Row',
        'DB Row',
        'back',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'T-Bar Row',
        null,
        'back',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Pull-Up',
        null,
        'back',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Chin-Up',
        null,
        'back',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Lat Pulldown',
        null,
        'back',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Neutral Grip Lat Pulldown',
        null,
        'back',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Straight-Arm Pulldown',
        null,
        'back',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Cable Pullover',
        null,
        'back',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Face Pull',
        null,
        'back',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Back Extension',
        null,
        'back',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Overhead Press',
        'OHP',
        'shoulders',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Seated Dumbbell Shoulder Press',
        'DB Shoulder Press',
        'shoulders',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Arnold Press',
        null,
        'shoulders',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Machine Shoulder Press',
        null,
        'shoulders',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Lateral Raise',
        null,
        'shoulders',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Cable Lateral Raise',
        null,
        'shoulders',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Rear Delt Fly',
        null,
        'shoulders',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Reverse Pec Deck',
        null,
        'shoulders',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Barbell Curl',
        null,
        'arms',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'EZ Bar Curl',
        null,
        'arms',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Incline Dumbbell Curl',
        null,
        'arms',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Preacher Curl',
        null,
        'arms',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Hammer Curl',
        null,
        'arms',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Cable Curl',
        null,
        'arms',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Triceps Pushdown',
        null,
        'arms',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Overhead Cable Triceps Extension',
        null,
        'arms',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Skull Crusher',
        null,
        'arms',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'JM Press',
        null,
        'arms',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Close Grip Push-Up',
        null,
        'arms',
        'push',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Plank',
        null,
        'core',
        'hold',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Side Plank',
        null,
        'core',
        'hold',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Dead Bug',
        null,
        'core',
        'hold',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Ab Wheel Rollout',
        'Ab Wheel',
        'core',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Hanging Leg Raise',
        null,
        'core',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Cable Crunch',
        null,
        'core',
        'pull',
        null,
        now (),
        now (),
        null
    ),
    (
        gen_random_uuid (),
        'Decline Sit-Up',
        null,
        'core',
        'pull',
        null,
        now (),
        now (),
        null
    );

commit;
